[package]
name = "aoc"
version = "0.1.0"
authors = ["Kevin Rowland <krowlan3@jhu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
